// <auto-generated />
namespace Castra.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addedcontext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcontext));
        
        string IMigrationMetadata.Id
        {
            get { return "201411081227585_addedcontext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
